# Hardware configuration adapted for EkaOS
# Original generated by 'nixos-generate-config'
{ config, lib, pkgs, ... }:

{
  # not-detected.nix equivalent
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/09aec90e-876f-4f7a-8e6b-1436eebc3c2a";
      fsType = "ext4";
    };

  fileSystems."/nix/store" =
    { device = "/dev/disk/by-uuid/ed79278c-6dc2-4256-aea9-84348f3c7733";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BCC0-ADD5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # swap.devices = [ ];  # EkaOS uses `swap` not `swapDevices`

  networking.useDHCP = lib.mkDefault true;

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
