{
  buildPerlPackage,
  fetchurl,
  lib,
  perl,
  stdenv,
}:
buildPerlPackage {
  pname = "DBI";
  version = "1.648";
  src = fetchurl {
    url = "mirror://cpan/authors/id/H/HM/HMBRAND/DBI-1.648.tgz";
    hash = "sha256-7yZqrWAQzi6rt+Rl69c8owILxYFQ9pib2Jwrj5usaoY=";
  };
  env = lib.optionalAttrs stdenv.cc.isGNU {
    NIX_CFLAGS_COMPILE = "-Wno-error=incompatible-pointer-types";
  };
  postInstall = lib.optionalString (perl ? crossVersion) ''
    mkdir -p $out/${perl.libPrefix}/cross_perl/${perl.version}/DBI
    cat > $out/${perl.libPrefix}/cross_perl/${perl.version}/DBI.pm <<EOF
    package DBI;
    BEGIN {
    our \$VERSION = "$version";
    }
    1;
    EOF

    autodir=$(echo $out/${perl.libPrefix}/${perl.version}/*/auto/DBI)
    cat > $out/${perl.libPrefix}/cross_perl/${perl.version}/DBI/DBD.pm <<EOF
    package DBI::DBD;
    use Exporter ();
    use vars qw (@ISA @EXPORT);
    @ISA = qw(Exporter);
    @EXPORT = qw(dbd_postamble);
    sub dbd_postamble {
        return '
    # --- This section was generated by DBI::DBD::dbd_postamble()
    DBI_INSTARCH_DIR=$autodir
    DBI_DRIVER_XST=$autodir/Driver.xst

    # The main dependency (technically correct but probably not used)
    \$(BASEEXT).c: \$(BASEEXT).xsi

    # This dependency is needed since MakeMaker uses the .xs.o rule
    \$(BASEEXT)\$(OBJ_EXT): \$(BASEEXT).xsi

    \$(BASEEXT).xsi: \$(DBI_DRIVER_XST) $autodir/Driver_xst.h
    ''\t\$(PERL) -p -e "s/~DRIVER~/\$(BASEEXT)/g" \$(DBI_DRIVER_XST) > \$(BASEEXT).xsi

    # ---
    ';
    }
    1;
    EOF
  '';
  meta = {
    description = "Database independent interface for Perl";
    homepage = "https://dbi.perl.org";
    license = with lib.licenses; [
      artistic1
      gpl1Plus
    ];
  };
}
