{
  lib,
  stdenv,
  fetchFromGitHub,
  autoreconfHook,
  pkg-config,
  glib,
  ncurses,
  libcap_ng,
  systemdMinimal,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "irqbalance";
  version = "1.9.5";

  src = fetchFromGitHub {
    owner = "Irqbalance";
    repo = "irqbalance";
    tag = "v${finalAttrs.version}";
    hash = "sha256-qbGyYpNXyw5bC4K/7E4v6qHEfLnUbamtzSfiEqJ0uY0=";
  };

  nativeBuildInputs = [
    autoreconfHook
    pkg-config
  ];

  buildInputs = [
    glib
    ncurses
    libcap_ng
    systemdMinimal
  ];

  configureFlags = [
    "--with-systemd"
    "systemdsystemunitdir=$$out/lib/systemd/system"
  ];

  postInstall = ''
    sed -i "/^EnvironmentFile=/d" "$out/lib/systemd/system/irqbalance.service"
    substituteInPlace "$out/lib/systemd/system/irqbalance.service" \
      --replace-fail /usr/sbin/irqbalance "$out/bin/irqbalance --journal" \
      --replace-fail ' $IRQBALANCE_ARGS' ""
  '';

  meta = {
    homepage = "https://github.com/Irqbalance/irqbalance";
    description = "Daemon to help balance the cpu load generated by interrupts across all of a systems cpus";
    license = lib.licenses.gpl2Only;
    platforms = lib.platforms.linux;
    mainProgram = "irqbalance";
  };
})
