# List of ekapkgs-specific EkaOS modules
# Loaded in addition to core-pkgs' base modules
[
  ./programs/acpi.nix
  ./programs/acpitool.nix
  ./programs/act.nix
  ./programs/age-plugin-yubikey.nix
  ./programs/aide.nix
  ./programs/alacritty.nix
  ./programs/angle-grinder.nix
  ./programs/argocd.nix
  ./programs/aria2.nix
  ./programs/asciinema.nix
  ./programs/atool.nix
  ./programs/atuin.nix
  ./programs/autossh.nix
  ./programs/aws-vault.nix
  ./programs/axel.nix
  ./programs/bandwhich.nix
  ./programs/banner.nix
  ./programs/bar.nix
  ./programs/bat.nix
  ./programs/bazelisk.nix
  ./programs/bc.nix
  ./programs/bdftopcf.nix
  ./programs/below.nix
  ./programs/bemenu.nix
  ./programs/binsider.nix
  ./programs/bmon.nix
  ./programs/borgbackup.nix
  ./programs/brightnessctl.nix
  ./programs/broot.nix
  ./programs/bspwm.nix
  ./programs/btop.nix
  ./programs/buf.nix
  ./programs/byobu.nix
  ./programs/cabextract.nix
  ./programs/calcurse.nix
  ./programs/cargo-audit.nix
  ./programs/cargo-bloat.nix
  ./programs/cargo-deny.nix
  ./programs/cargo-expand.nix
  ./programs/cargo-hack.nix
  ./programs/cargo-insta.nix
  ./programs/cargo-make.nix
  ./programs/cargo-outdated.nix
  ./programs/cargo-tarpaulin.nix
  ./programs/cargo-watch.nix
  ./programs/catatonit.nix
  ./programs/catimg.nix
  ./programs/cbonsai.nix
  ./programs/chafa.nix
  ./programs/cheat.nix
  ./programs/chezmoi.nix
  ./programs/choose.nix
  ./programs/cloudflared.nix
  ./programs/cmatrix.nix
  ./programs/cmus.nix
  ./programs/cocogitto.nix
  ./programs/comrak.nix
  ./programs/consul.nix
  ./programs/containerd.nix
  ./programs/convmv.nix
  ./programs/cowsay.nix
  ./programs/cpufetch.nix
  ./programs/cpuset.nix
  ./programs/croc.nix
  ./programs/cronie.nix
  ./programs/csvlens.nix
  ./programs/csvtk.nix
  ./programs/ctop.nix
  ./programs/dasel.nix
  ./programs/dateutils.nix
  ./programs/ddclient.nix
  ./programs/ddns-go.nix
  ./programs/delta.nix
  ./programs/detox.nix
  ./programs/difftastic.nix
  ./programs/direnv.nix
  ./programs/dive.nix
  ./programs/dmenu.nix
  ./programs/dmidecode.nix
  ./programs/dnscrypt-proxy.nix
  ./programs/dnsmasq.nix
  ./programs/docker-compose.nix
  ./programs/doctl.nix
  ./programs/doggo.nix
  ./programs/dog.nix
  ./programs/dool.nix
  ./programs/dprint.nix
  ./programs/drill.nix
  ./programs/dtach.nix
  ./programs/dua.nix
  ./programs/du-dust.nix
  ./programs/duf.nix
  ./programs/dumb-init.nix
  ./programs/dunst.nix
  ./programs/duplicity.nix
  ./programs/earlyoom.nix
  ./programs/editorconfig.nix
  ./programs/ed.nix
  ./programs/eksctl.nix
  ./programs/elvish.nix
  ./programs/entr.nix
  ./programs/erdtree.nix
  ./programs/espeak.nix
  ./programs/ethtool.nix
  ./programs/exercism.nix
  ./programs/eza.nix
  ./programs/fail2ban.nix
  ./programs/fcp.nix
  ./programs/fdupes.nix
  ./programs/ffuf.nix
  ./programs/figlet.nix
  ./programs/fish.nix
  ./programs/flashrom.nix
  ./programs/flite.nix
  ./programs/fluidsynth.nix
  ./programs/fonttosfnt.nix
  ./programs/fzf.nix
  ./programs/genact.nix
  ./programs/gh-dash.nix
  ./programs/git-absorb.nix
  ./programs/git-branchless.nix
  ./programs/git-bug.nix
  ./programs/git-chglog.nix
  ./programs/git-cliff.nix
  ./programs/git-interactive-rebase-tool.nix
  ./programs/gitui.nix
  ./programs/gitu.nix
  ./programs/glab.nix
  ./programs/glow.nix
  ./programs/gnuplot.nix
  ./programs/gomplate.nix
  ./programs/goreleaser.nix
  ./programs/go-task.nix
  ./programs/gotop.nix
  ./programs/greetd.nix
  ./programs/grim.nix
  ./programs/grpcui.nix
  ./programs/grpcurl.nix
  ./programs/gum.nix
  ./programs/haproxy.nix
  ./programs/hdparm.nix
  ./programs/headscale.nix
  ./programs/helix.nix
  ./programs/helm-docs.nix
  ./programs/hexd.nix
  ./programs/hexedit.nix
  ./programs/hexyl.nix
  ./programs/htop.nix
  ./programs/httpx.nix
  ./programs/hugo.nix
  ./programs/hyperfine.nix
  ./programs/hysteria.nix
  ./programs/i3.nix
  ./programs/iftop.nix
  ./programs/ijq.nix
  ./programs/imagemagick.nix
  ./programs/inadyn.nix
  ./programs/inxi.nix
  ./programs/iotop-c.nix
  ./programs/iperf3.nix
  ./programs/ipmitool.nix
  ./programs/irqbalance.nix
  ./programs/irssi.nix
  ./programs/jdupes.nix
  ./programs/jless.nix
  ./programs/jo.nix
  ./programs/joshuto.nix
  ./programs/jp2a.nix
  ./programs/kanshi.nix
  ./programs/keychain.nix
  ./programs/ko.nix
  ./programs/kubectl-cnpg.nix
  ./programs/kubeseal.nix
  ./programs/kubeval.nix
  ./programs/lazygit.nix
  ./programs/ldns.nix
  ./programs/less.nix
  ./programs/lf.nix
  ./programs/lighttpd.nix
  ./programs/lsd.nix
  ./programs/lshw.nix
  ./programs/lsof.nix
  ./programs/lxterminal.nix
  ./programs/lynis.nix
  ./programs/lynx.nix
  ./programs/lz4.nix
  ./programs/lzip.nix
  ./programs/macchina.nix
  ./programs/mako.nix
  ./programs/man-db.nix
  ./programs/mcfly.nix
  ./programs/mc.nix
  ./programs/mdbook-mermaid.nix
  ./programs/mdbook-toc.nix
  ./programs/mediainfo.nix
  ./programs/memtester.nix
  ./programs/meson.nix
  ./programs/micro.nix
  ./programs/miller.nix
  ./programs/minicom.nix
  ./programs/minio-client.nix
  ./programs/minio.nix
  ./programs/mise.nix
  ./programs/mkfontscale.nix
  ./programs/mosh.nix
  ./programs/mosquitto.nix
  ./programs/most.nix
  ./programs/mtr.nix
  ./programs/mupdf.nix
  ./programs/mutt.nix
  ./programs/ncdu.nix
  ./programs/ncmpcpp.nix
  ./programs/nethogs.nix
  ./programs/newsboat.nix
  ./programs/nginx.nix
  ./programs/ngrep.nix
  ./programs/nikto.nix
  ./programs/nitrocli.nix
  ./programs/nitrogen.nix
  ./programs/nload.nix
  ./programs/nmap.nix
  ./programs/nnn.nix
  ./programs/nomad.nix
  ./programs/nuclei.nix
  ./programs/numactl.nix
  ./programs/nvi.nix
  ./programs/nyancat.nix
  ./programs/oath-toolkit.nix
  ./programs/oauth2c.nix
  ./programs/oauth2-proxy.nix
  ./programs/oh-my-posh.nix
  ./programs/onefetch.nix
  ./programs/openvpn.nix
  ./programs/optipng.nix
  ./programs/oxipng.nix
  ./programs/pam_u2f.nix
  ./programs/parallel.nix
  ./programs/parted.nix
  ./programs/pass-git-helper.nix
  ./programs/pass.nix
  ./programs/pdfcpu.nix
  ./programs/pdfgrep.nix
  ./programs/peaclock.nix
  ./programs/peco.nix
  ./programs/pfetch.nix
  ./programs/pgformatter.nix
  ./programs/picom.nix
  ./programs/pigz.nix
  ./programs/pinentry.nix
  ./programs/pipes-rs.nix
  ./programs/pixz.nix
  ./programs/pngquant.nix
  ./programs/podman-compose.nix
  ./programs/podman-tui.nix
  ./programs/polybar.nix
  ./programs/ponysay.nix
  ./programs/powertop.nix
  ./programs/privoxy.nix
  ./programs/procs.nix
  ./programs/progress.nix
  ./programs/prometheus-node-exporter.nix
  ./programs/proxychains.nix
  ./programs/pv.nix
  ./programs/qpdf.nix
  ./programs/rage.nix
  ./programs/ranger.nix
  ./programs/rdfind.nix
  ./programs/redshift.nix
  ./programs/reflex.nix
  ./programs/rename.nix
  ./programs/reptyr.nix
  ./programs/restic.nix
  ./programs/ripgrep.nix
  ./programs/rm-improved.nix
  ./programs/rofi.nix
  ./programs/rustscan.nix
  ./programs/rxvt-unicode.nix
  ./programs/s3cmd.nix
  ./programs/s5cmd.nix
  ./programs/scdoc.nix
  ./programs/screen.nix
  ./programs/sd.nix
  ./programs/shellharden.nix
  ./programs/shfmt.nix
  ./programs/sing-box.nix
  ./programs/skaffold.nix
  ./programs/slides.nix
  ./programs/sl.nix
  ./programs/slurp.nix
  ./programs/smartmontools.nix
  ./programs/socat.nix
  ./programs/soft-serve.nix
  ./programs/sops.nix
  ./programs/sox.nix
  ./programs/spectrwm.nix
  ./programs/ssh-audit.nix
  ./programs/sshguard.nix
  ./programs/sshpass.nix
  ./programs/sshuttle.nix
  ./programs/stalonetray.nix
  ./programs/starship.nix
  ./programs/step-cli.nix
  ./programs/stgit.nix
  ./programs/st.nix
  ./programs/streamripper.nix
  ./programs/stress-ng.nix
  ./programs/stress.nix
  ./programs/stunnel.nix
  ./programs/stylua.nix
  ./programs/svgcleaner.nix
  ./programs/swappy.nix
  ./programs/swaybg.nix
  ./programs/sway-launcher-desktop.nix
  ./programs/swaylock.nix
  ./programs/swayr.nix
  ./programs/sxhkd.nix
  ./programs/syncthing.nix
  ./programs/sysstat.nix
  ./programs/tailspin.nix
  ./programs/taplo.nix
  ./programs/taskwarrior.nix
  ./programs/tcptraceroute.nix
  ./programs/tealdeer.nix
  ./programs/terraform-ls.nix
  ./programs/terragrunt.nix
  ./programs/texlab.nix
  ./programs/thermald.nix
  ./programs/tig.nix
  ./programs/timewarrior.nix
  ./programs/tini.nix
  ./programs/tiv.nix
  ./programs/tmate.nix
  ./programs/tmuxinator.nix
  ./programs/tmux-mem-cpu-load.nix
  ./programs/tofi.nix
  ./programs/toilet.nix
  ./programs/tokei.nix
  ./programs/topgrade.nix
  ./programs/tor.nix
  ./programs/torsocks.nix
  ./programs/traceroute.nix
  ./programs/trash-cli.nix
  ./programs/tre-command.nix
  ./programs/tree.nix
  ./programs/trippy.nix
  ./programs/trufflehog.nix
  ./programs/tty-clock.nix
  ./programs/umoci.nix
  ./programs/units.nix
  ./programs/unrar.nix
  ./programs/usbutils.nix
  ./programs/viddy.nix
  ./programs/vifm.nix
  ./programs/vim.nix
  ./programs/vivid.nix
  ./programs/watchdog.nix
  ./programs/watchexec.nix
  ./programs/wavemon.nix
  ./programs/wayclip.nix
  ./programs/way-displays.nix
  ./programs/wayshot.nix
  ./programs/websocat.nix
  ./programs/wemux.nix
  ./programs/wev.nix
  ./programs/whois.nix
  ./programs/wl-clipboard.nix
  ./programs/wlogout.nix
  ./programs/wlr-randr.nix
  ./programs/wlsunset.nix
  ./programs/wofi.nix
  ./programs/wtype.nix
  ./programs/xautolock.nix
  ./programs/xclip.nix
  ./programs/xdotool.nix
  ./programs/xh.nix
  ./programs/xmlstarlet.nix
  ./programs/xplr.nix
  ./programs/xq-xml.nix
  ./programs/xsel.nix
  ./programs/xss-lock.nix
  ./programs/yamlfmt.nix
  ./programs/yazi.nix
  ./programs/yj.nix
  ./programs/yubikey-agent.nix
  ./programs/zathura.nix
  ./programs/zoxide.nix
  ./programs/zsh.nix
]
