{
  lib,
  stdenv,
  fetchFromGitHub,
  cmake,
  nasm,
  zlib,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "isa-l";
  version = "2.32.1";

  __structuredAttrs = true;
  strictDeps = true;

  src = fetchFromGitHub {
    owner = "intel";
    repo = "isa-l";
    tag = "v${finalAttrs.version}";
    hash = "sha256-JizQXhfDCL8aWEv52TBuXw06HA/8t7Ram/q9vSp5/DI=";
  };

  nativeBuildInputs = [
    cmake
    cmake.configurePhaseHook
    nasm
  ];

  buildInputs = [
    zlib
  ];

  env = {
    NIX_CFLAGS_COMPILE = toString [
      "-DVERSION=\"${finalAttrs.version}\""
    ];
  };
  cmakeFlags = [
    (lib.cmakeBool "ISAL_BUILD_IGZIP_CLI" true)
  ];

  # Fix broken paths in .pc file generated by cmake
  postInstall = ''
    sed -i "s|libdir=.*|libdir=$out/lib|" $out/lib/pkgconfig/libisal.pc
    sed -i "s|includedir=.*|includedir=$out/include|" $out/lib/pkgconfig/libisal.pc
  '';

  doCheck = true;

  meta = {
    description = "Collection of optimised low-level functions targeting storage applications";
    mainProgram = "igzip";
    license = lib.licenses.bsd3;
    homepage = "https://github.com/intel/isa-l";
    changelog = "https://github.com/intel/isa-l/releases/tag/v${finalAttrs.version}";
    platforms = lib.platforms.all;
  };
})
