{
  lib,
  stdenv,
  fetchurl,
}:

stdenv.mkDerivation (finalAttrs: {
  pname = "bibutils";
  version = "7.2";

  src = fetchurl {
    url = "mirror://sourceforge/bibutils/bibutils_${finalAttrs.version}_src.tgz";
    sha256 = "sha256-bgKK7x6Kaz5azvCYWEp7tocI81z+dAEbNBwR/qXktcM=";
  };

  # the configure script is not generated by autoconf
  # and does not recognize --build/--host cross compilation flags
  configurePlatforms = [ ];

  configureFlags = [
    "--dynamic"
    "--install-dir"
    "$(out)/bin"
    "--install-lib"
    "$(out)/lib"
  ];

  dontAddPrefix = true;

  makeFlags = [
    "CC:=$(CC)"
  ];

  meta = {
    description = "Bibliography format interconversion";
    homepage = "https://sourceforge.net/p/bibutils/home/Bibutils/";
    license = lib.licenses.gpl2Only;
    platforms = lib.platforms.unix;
  };
})
